# Generated by Django 5.0 on 2024-05-15 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_mun', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('nom_mun_corto', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nom_mun_largo', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('img_mun', models.ImageField(blank=True, default=None, null=True, upload_to='img/img_mun')),
            ],
            options={
                'ordering': ['cve_mun'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.TextField(blank=True, default=None, null=True)),
                ('url', models.TextField(blank=True, default=None, null=True)),
                ('archivo', models.FileField(blank=True, default=None, null=True, upload_to='docs')),
                ('posicion', models.IntegerField(blank=True, default=None, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmduoet.municipio')),
            ],
            options={
                'ordering': ['municipio', 'posicion'],
            },
        ),
    ]
