# Generated by Django 5.0 on 2024-05-17 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmduoet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pmduoet.municipio'),
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('tipo', models.TextField(blank=True, choices=[('parcial', 'Programa parcial'), ('municipal', 'Programa municipal')], default='diagnostico', help_text='Tipo de avance', max_length=20)),
                ('status', models.TextField(blank=True, choices=[('diagnostico', 'Diagnóstico'), ('elaboracion', 'Elaboración'), ('dictaminacion', 'Dictaminación'), ('revision', 'Revisión'), ('dictaminado', 'Dictaminado'), ('publicado', 'Publicado'), ('pendiente', 'Pendiente')], default='diagnostico', help_text='Status del avance', max_length=20)),
                ('dictaminacion', models.DateField(blank=True, null=True)),
                ('publicacion', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pmduoet.municipio')),
            ],
        ),
    ]
