# Generated by Django 5.0 on 2024-05-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmduoet', '0002_alter_documento_municipio_avance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='dictaminacion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='avance',
            name='tipo',
            field=models.TextField(blank=True, choices=[('parcial', 'Programa parcial'), ('municipal', 'Programa municipal')], default='municipal', help_text='Tipo de avance', max_length=20),
        ),
    ]
