# Generated by Django 5.0 on 2024-05-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmduoet', '0003_alter_avance_dictaminacion_alter_avance_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='status',
            field=models.TextField(blank=True, choices=[('diagnostico', 'Diagnóstico'), ('elaboracion', 'Elaboración'), ('dictaminacion', 'Dictaminación'), ('revision', 'Revisión'), ('dictaminado', 'Dictaminado'), ('publicado', 'Publicado'), ('pendiente', 'Pendiente')], default='diagnostico', help_text='Status del avance', max_length=20),
        ),
    ]
