# Generated by Django 5.0 on 2024-05-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmduoet', '0005_alter_municipio_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='status',
        ),
    ]
