# Generated by Django 5.0 on 2024-05-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmduoet', '0006_remove_municipio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='status',
            field=models.TextField(blank=True, choices=[('diagnostico', 'Diagnóstico'), ('elaboracion', 'Elaboración'), ('dictaminacion', 'Dictaminación'), ('revision', 'Revisión'), ('dictaminado', 'Dictaminado'), ('publicado', 'Publicado'), ('pendiente', 'Pendiente')], help_text='Status del avance', max_length=20),
        ),
    ]
