# Generated by Django 5.0 on 2024-05-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmduoet', '0007_municipio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
